In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pip
import seaborn as sns

!pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in d:\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in d:\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in d:\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [2]:
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
!pip install catboost
!pip install xgboost

Requirement already satisfied: catboost in d:\anaconda3\lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in d:\anaconda3\lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in d:\anaconda3\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in d:\anaconda3\lib\site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas<4.0,>=0.24 in d:\anaconda3\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in d:\anaconda3\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in d:\anaconda3\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in d:\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda3\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in d:\anaconda3\lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in d:\anaconda3\lib\site-packages (from plotly->catboost) (2.7.0)
Requirement already satisfied: xgboost in d:\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in d:\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in d:\anaconda3\lib\site-packages (from xgboost) (1.16.3)

In [4]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV


import warnings

In [5]:
import sys
print(sys.executable)
print(sys.version)

c:\Users\aarav\AppData\Local\Programs\Python\Python39\python.exe
3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]

In [6]:
import sys
!{sys.executable} -m pip install catboost xgboost lightgbm

Requirement already satisfied: catboost in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (1.2.10)
Requirement already satisfied: xgboost in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (2.1.4)
Requirement already satisfied: lightgbm in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (4.6.0)
Requirement already satisfied: plotly in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from catboost) (6.7.0)
Requirement already satisfied: matplotlib in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from catboost) (3.9.4)
Requirement already satisfied: scipy in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from catboost) (1.13.1)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from catboost) (2.0.2)
Requirement already satisfied: graphviz in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from catboost) (0.21)
Requirement already satisfied: six in c:\users\aarav\appdata\roaming\python\python39\site-packages (from catboost) (1.17.0)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from plotly->catboost) (2.19.0)
Requirement already satisfied: packaging in c:\users\aarav\appdata\roaming\python\python39\site-packages (from plotly->catboost) (25.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->catboost) (4.60.2)
Requirement already satisfied: cycler>=0.10 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: importlib-resources>=3.2.0; python_version < "3.10" in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->catboost) (6.5.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: pillow>=8 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aarav\appdata\roaming\python\python39\site-packages (from matplotlib->catboost) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->catboost) (1.3.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->catboost) (1.4.7)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\aarav\appdata\local\programs\python\python39\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in c:\users\aarav\appdata\roaming\python\python39\site-packages (from importlib-resources>=3.2.0; python_version < "3.10"->matplotlib->catboost) (3.23.0)

WARNING: You are using pip version 20.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\aarav\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [7]:
from catboost import CatBoostRegressor

In [8]:
from xgboost import XGBRegressor

In [9]:
df=pd.read_csv('data/stud.csv')

In [10]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [11]:
x=df.drop(columns=['math_score'],axis=1)

In [12]:
x.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [13]:
y=df['math_score']

In [14]:
y.head()

0    72
1    69
2    90
3    47
4    76
Name: math_score, dtype: int64

In [16]:
#create column transformer with 3 types of transformers
num_features=x.select_dtypes(exclude=['object']).columns
cat_features=x.select_dtypes(include=['object']).columns

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

In [17]:
x=preprocessor.fit_transform(x)

In [18]:
x

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]])

In [20]:
x.shape

(1000, 19)

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train.shape, x_test.shape

((800, 19), (200, 19))